# Generated by Django 5.1.3 on 2025-01-03 02:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronym', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='accounts')),
                ('birthday_date', models.DateField(blank=True, max_length=10, null=True, verbose_name='Дата рождения')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Электронная почта')),
                ('position', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Должность')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=15, null=True, verbose_name='Дом')),
                ('structure', models.CharField(blank=True, max_length=15, null=True, verbose_name='Корпус')),
                ('building', models.CharField(blank=True, max_length=15, null=True, verbose_name='Строение')),
                ('apartment', models.CharField(blank=True, max_length=15, null=True, verbose_name='Квартира')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('telegram', models.CharField(max_length=50, verbose_name='Телеграм')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Контакты пользователя',
                'verbose_name_plural': 'Список контактов пользователя',
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(blank=True, max_length=250, null=True, verbose_name='Организация')),
                ('education_level', models.CharField(blank=True, max_length=15, null=True, verbose_name='Уровень образования')),
                ('serial_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер диплома')),
                ('register_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Регистрационный номер')),
                ('speciality', models.CharField(max_length=50, verbose_name='Специальность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Диплом',
                'verbose_name_plural': 'Дипломы',
            },
        ),
        migrations.CreateModel(
            name='Military_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gd', models.CharField(blank=True, max_length=7, null=True, verbose_name='ГД')),
                ('personal_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Личный номер')),
                ('released', models.CharField(blank=True, max_length=100, null=True, verbose_name='Выдан')),
                ('release_data_day', models.CharField(blank=True, max_length=2, null=True, verbose_name='День выдачи')),
                ('release_data_month', models.CharField(blank=True, max_length=2, null=True, verbose_name='Месяц выдачи')),
                ('release_data_year', models.CharField(blank=True, max_length=4, null=True, verbose_name='Год выдачи')),
                ('rank', models.CharField(blank=True, max_length=50, null=True, verbose_name='Воинское звание')),
                ('order', models.CharField(blank=True, max_length=100, null=True, verbose_name='Присвоено приказом')),
                ('military_specialty', models.CharField(blank=True, max_length=10, null=True, verbose_name='ВУС №')),
                ('profile_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Наименование профиля')),
                ('reserve_num', models.CharField(blank=True, max_length=10, null=True, verbose_name='Разряд запаса')),
                ('mil_service', models.CharField(blank=True, max_length=10, null=True, verbose_name='Проходил службу с... по...')),
                ('pinned', models.CharField(blank=True, max_length=10, null=True, verbose_name='Прикреплен или снят с учета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_service', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Военный билет',
                'verbose_name_plural': 'Военные билеты',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_serial_number', models.CharField(blank=True, max_length=4, null=True, verbose_name='Серия')),
                ('passport_num', models.CharField(blank=True, max_length=6, null=True, verbose_name='Номер паспорта')),
                ('released', models.CharField(blank=True, max_length=200, null=True, verbose_name='Выдан')),
                ('released_data', models.CharField(blank=True, max_length=10, null=True, verbose_name='Дата выдачи')),
                ('department_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код подразделения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорта',
            },
        ),
    ]
